### ISSUE TITLE
NVP6134 Docs

### ISSUE THREAD

**Issue by Anton-Kosenko** [4e4o/nvp6134_ex_170306#1]
Hi, Mr 4e40!

Judging by this project, you have a full documentation for NVP6134 IC. Is it possible for you to share this docs with me? 
I would be very gratefull you for this.

My email is kosenko.ank.97@mail.ru

Thanks in advance

**Comment by 4e4o** [comment]
Hi, sure. Here is what i got.

  
>Четверг, 20 мая 2021, 12:34 +03:00 от Anton Kosenko ***@***.***>:
> 
> 
>Hi, Mr 4e40!
>Judging by this project, you have a full documentation for NVP6134 IC. Is it possible for you to share this docs with me?
>I would be very gratefull you for this.
>My email is  ***@***.***
>Thanks in advance
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
Тереполумбо

**Comment by Anton-Kosenko** [comment]
Actually, I don't understand what "Тереполумбо" mean.

**Comment by 4e4o** [comment]
I send archive via email.

**Comment by 4e4o** [comment]
Do you receive it?

**Comment by 4e4o** [comment]
Added datasheet. See docs directory
